apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: svsf4h1m6-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-fbe39239d5.nj2d.p3.openshiftapps.com/rhtap/rhtap-qe:8d118c7da5288e79311b03f96f5975df111e90d4@sha256:1c18d9b088bd0ddfd3f3dc757b8a1ab75bed8339e70140b041874865cf2e3fa7
          name: container-image
